// Wait for the Wasm module to be ready
let Module = null;
let cpp = null; // will hold exported functions

// Load the module generated by Emscripten (CakeClicker.js)
import ModuleLoader from './CakeClicker.js';

async function init() {
    Module = await ModuleLoader();
    // Now we can call C++ functions via Embind (they are attached to Module)
    cpp = Module;

    // UI elements
    const cakeDiv = document.getElementById('cake');
    const iconSlider = document.getElementById('iconSlider');
    const sliderIconSpan = document.getElementById('sliderIcon');
    const scoreSpan = document.getElementById('scoreValue');
    const multiplierSpan = document.getElementById('multiplier');
    const passiveSpan = document.getElementById('passive');
    const upgradeClickBtn = document.getElementById('upgradeClick');
    const upgradePassiveBtn = document.getElementById('upgradePassive');
    const resetBtn = document.getElementById('resetBtn');

    const icons = ['🍰', '🍪', '🍕', '🍔', '🍎'];

    iconSlider.addEventListener('input', (event) => {
        const idx = parseInt(event.target.value);
        const newIcon = icons[idx];
        cakeDiv.innerText = newIcon;
        sliderIconSpan.innerText = newIcon;
    });
    // Helper to update UI from C++ state

    iconSlider.dispatchEvent(new Event('input'))

    function updateUI() {
        scoreSpan.innerText = Math.floor(cpp.getScore());
        multiplierSpan.innerText = cpp.getClickMultiplier();
        passiveSpan.innerText = cpp.getPassiveIncome().toFixed(1);
    }

    // Create a floating "+X" effect at click position
    function showFloatingNumber(x, y, points) {
        const el = document.createElement('div');
        el.className = 'floating-number';
        el.innerText = `+${points}`;
        el.style.left = `${x - 20}px`;
        el.style.top = `${y - 30}px`;
        document.body.appendChild(el);
        setTimeout(() => el.remove(), 800);
    }

    // Click handler on the cake
    cakeDiv.addEventListener('click', (event) => {
        // Get click coordinates for floating number
        const rect = cakeDiv.getBoundingClientRect();
        const centerX = rect.left + rect.width / 2;
        const centerY = rect.top + rect.height / 2;

        // Tell C++ to add score (multiplier applied inside C++)
        cpp.addScore(1);   // base 1 point, multiplier is applied in C++

        // Update UI
        updateUI();

        // Show floating number with total gain = multiplier
        const mult = cpp.getClickMultiplier();
        showFloatingNumber(centerX, centerY, mult);

        // Add a little 'pop' animation
        cakeDiv.style.transform = 'scale(1.1)';
        setTimeout(() => cakeDiv.style.transform = '', 100);
    });

    // Upgrade buttons
    upgradeClickBtn.addEventListener('click', () => {
        cpp.buyUpgrade(0);
        updateUI();
    });
    upgradePassiveBtn.addEventListener('click', () => {
        cpp.buyUpgrade(1);
        updateUI();
    });
    resetBtn.addEventListener('click', () => {
        cpp.reset();
        updateUI();
    });

    // Passive income update loop (call C++ update every frame)
    let lastTimestamp = performance.now();
    function gameLoop(now) {
        let delta = Math.min(0.1, (now - lastTimestamp) / 1000); // seconds
        lastTimestamp = now;
        if (delta > 0) {
            cpp.update(delta);
            updateUI();
        }
        requestAnimationFrame(gameLoop);
    }
    requestAnimationFrame(gameLoop);

    // Initial UI refresh
    updateUI();
    console.log("Cake Clicker ready! Click the cake 🍰");
}

init();